//go:build !disable_pgv
// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/extensions/load_balancing_policies/least_response_time/v3/least_response_time.proto

package least_response_timev3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LeastResponseTime with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LeastResponseTime) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LeastResponseTime with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LeastResponseTimeMultiError, or nil if none found.
func (m *LeastResponseTime) ValidateAll() error {
	return m.validate(true)
}

func (m *LeastResponseTime) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if wrapper := m.GetChoiceCount(); wrapper != nil {

		if wrapper.GetValue() < 2 {
			err := LeastResponseTimeValidationError{
				field:  "ChoiceCount",
				reason: "value must be greater than or equal to 2",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if all {
		switch v := interface{}(m.GetActiveRequestBias()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LeastResponseTimeValidationError{
					field:  "ActiveRequestBias",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LeastResponseTimeValidationError{
					field:  "ActiveRequestBias",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetActiveRequestBias()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LeastResponseTimeValidationError{
				field:  "ActiveRequestBias",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSlowStartConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LeastResponseTimeValidationError{
					field:  "SlowStartConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LeastResponseTimeValidationError{
					field:  "SlowStartConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSlowStartConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LeastResponseTimeValidationError{
				field:  "SlowStartConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLocalityLbConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LeastResponseTimeValidationError{
					field:  "LocalityLbConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LeastResponseTimeValidationError{
					field:  "LocalityLbConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLocalityLbConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LeastResponseTimeValidationError{
				field:  "LocalityLbConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEnableFullScan()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LeastResponseTimeValidationError{
					field:  "EnableFullScan",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LeastResponseTimeValidationError{
					field:  "EnableFullScan",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEnableFullScan()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LeastResponseTimeValidationError{
				field:  "EnableFullScan",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if _, ok := LeastResponseTime_SelectionMethod_name[int32(m.GetSelectionMethod())]; !ok {
		err := LeastResponseTimeValidationError{
			field:  "SelectionMethod",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LeastResponseTimeMultiError(errors)
	}

	return nil
}

// LeastResponseTimeMultiError is an error wrapping multiple validation errors
// returned by LeastResponseTime.ValidateAll() if the designated constraints
// aren't met.
type LeastResponseTimeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LeastResponseTimeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LeastResponseTimeMultiError) AllErrors() []error { return m }

// LeastResponseTimeValidationError is the validation error returned by
// LeastResponseTime.Validate if the designated constraints aren't met.
type LeastResponseTimeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LeastResponseTimeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LeastResponseTimeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LeastResponseTimeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LeastResponseTimeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LeastResponseTimeValidationError) ErrorName() string {
	return "LeastResponseTimeValidationError"
}

// Error satisfies the builtin error interface
func (e LeastResponseTimeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLeastResponseTime.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LeastResponseTimeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LeastResponseTimeValidationError{}
